/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/IX5H3PCXbCj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Arimo } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import sparkLogo from "../../app/spark_logo.svg"
import Image from "next/image"
import heroImage from "../../app/hero.jpeg"

export function Landing() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center bg-background">
        <Link href="#" className="flex items-center justify-center gap-1" prefetch={false}>
          <Image src={sparkLogo} alt="Spark" width={36} height={36} />
          <span className="text-black text-xl">spark</span>
        </Link>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-12 xl:gap-24">
            <div className="space-y-4">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
                Enciende tu <span className="text-[#5ce1e6]">carrera</span>. Codifica tu <span className="text-[#8c52ff]">futuro</span>.
              </h1>
              <p className="max-w-[600px] text-muted-foreground md:text-xl">
                Spark conecta talentos emergentes de desarrolladores con oportunidades emocionantes en empresas
                innovadoras.
              </p>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Inicia el test
                </Link>
              </div>
            </div>
            <Image
              src={heroImage}
              width="550"
              height="550"
              alt="Hero"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
            />
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container grid gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Acerca de Spark</h2>
              <p className="max-w-[600px] text-muted-foreground md:text-xl">
                Spark es una plataforma que conecta a desarrolladores emergentes con oportunidades emocionantes en
                empresas innovadoras. Nuestro objetivo es encender la carrera de los mejores talentos y ayudar a las
                empresas a encontrar a los desarrolladores que necesitan.
              </p>
            </div>
            <div className="grid gap-6">
              <div className="grid gap-1 rounded-lg bg-background p-4">
                <h3 className="text-xl font-bold">Para desarrolladores</h3>
                <p className="text-muted-foreground">
                  Encuentra oportunidades de trabajo emocionantes en empresas innovadoras. Crece tu carrera y aprende de
                  los mejores.
                </p>
              </div>
              <div className="grid gap-1 rounded-lg bg-background p-4">
                <h3 className="text-xl font-bold">Para empresas</h3>
                <p className="text-muted-foreground">
                  Contrata a los mejores talentos emergentes y lleva tu empresa al siguiente nivel. Nosotros nos
                  encargamos de encontrar a los desarrolladores perfectos para ti.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid gap-6 px-4 md:px-6 lg:grid-cols-3 lg:gap-12">
            <div className="grid gap-1 rounded-lg bg-background p-4">
              <RocketIcon />
              <h3 className="text-xl font-bold">Impulsa tu carrera</h3>
              <p className="text-muted-foreground">
                Encuentra oportunidades de trabajo emocionantes que te ayudarán a crecer y desarrollar tus habilidades.
              </p>
            </div>
            <div className="grid gap-1 rounded-lg bg-background p-4">
              <BriefcaseIcon />
              <h3 className="text-xl font-bold">Contrata al mejor talento</h3>
              <p className="text-muted-foreground">
                Accede a una red de desarrolladores emergentes y encuentra al candidato perfecto para tu empresa.
              </p>
            </div>
            <div className="grid gap-1 rounded-lg bg-background p-4">
              <BoltIcon />
              <h3 className="text-xl font-bold">Enciende tu futuro</h3>
              <p className="text-muted-foreground">
                Spark te ayudará a dar el siguiente paso en tu carrera o a encontrar al desarrollador que necesitas.
              </p>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t bg-muted">
        <p className="text-xs text-muted-foreground">&copy; 2024 Spark. Todos los derechos reservados.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4 text-muted-foreground" prefetch={false}>
            Términos de Servicio
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4 text-muted-foreground" prefetch={false}>
            Privacidad
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function BoltIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
      <circle cx="12" cy="12" r="4" />
    </svg>
  )
}


function BriefcaseIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  )
}


function RocketIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>
  )
}
